version: '3.7'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/companydb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - backend

volumes:
  db-data:
    driver: local

networks:
  backend: